apiVersion: v2
name: prod-msa-01
description: Chart for production

type: application

version: 0.0.1

appVersion: "1.0.0"

dependencies:
- name: app
  version: 0.1.0
  repository: https://chanmi910.github.io/helm-repo/charts
