apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.label}}-{{ .Values.name}}-deployment
  labels:
    app: {{ .Values.label}}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.label}}
  template:
    metadata:
      labels:
        app: {{ .Values.label}}
    spec:
      containers:
      - name: {{ .Values.name}}
        image: {{ .Values.image}}
        ports:
        - containerPort: 8080
